### Health Check
# GET http://localhost:3000/api/auth/health
# ngrok-skip-browser-warning: true

# ### Register
# POST http://localhost:3000/api/auth/register
# Content-Type: application/json
# # ngrok-skip-browser-warning: true

# {
#     "name": "Sujan Thapa",
#     "username": "sujan",
#     "email": "sujan@gmail.com",
#     "password": "password123"
# }


# POST http://localhost:3000/api/auth/login
# Content-Type: application/json

# {
#     "identifier": "sujan@gmail.com",
#     "password": "password123"
# }


# POST http://localhost:3000/api/chat/stream
# Content-Type: application/json

# {
#     "message": "teach me about maths",
#     "mode": "research",
#     "chatId": "cmn4fhtdi0000jcuj95wexnv0"
# }

# POST http://localhost:3000/api/chat/new
# Content-Type: application/json

# {
#   "email": "sujan@gmail.com",
#   "title": "My First Chat"
# }


# POST http://localhost:3000/api/chat/get
# Content-Type: application/json

# {
#   "email": "sujan@gmail.com",
#  "chatId": "cmn4yqwow0000coujhnybnx60"
# }



POST http://localhost:3000/api/user/assistant
Content-Type: application/json

{
 "assistantmode": "direct"
}

